### ISSUE TITLE
Xcode 10.1 报错

### ISSUE THREAD

**Issue by qingweiiOS** [fanbaoying/FBYBankCardRecognition-iOS#8]
Undefined symbols for architecture arm64:
  "_ZIM_SaveImage", referenced from:
      ImgSave(tagIMG, char const*) in libbexbankcard.a(gjimage.o)
  "_ZIM_LoadImage", referenced from:
      ImgLoad(tagIMG&, char const*) in libbexbankcard.a(gjimage.o)
  "_ZIM_DoneImage", referenced from:
      ImgLoad(tagIMG&, char const*) in libbexbankcard.a(gjimage.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

gjimage 没看到这玩意在那儿啊

**Comment by qingweiiOS** [comment]
自己的问题 没有修改 ENABLE_TESTABILITY

**Comment by wongshouxin** [comment]
您好，我也有相同的问题， ENABLE_TESTABILITY 也设置了NO，还是在Xcode16上报错，请问如何解决

**Comment by yaoming111** [comment]
Xcode16 上报错

**Comment by yaoming111** [comment]
@wongshouxin Xcode16上报错的问题解决了吗？

**Comment by TMacChen** [comment]
> [@wongshouxin](https://github.com/wongshouxin) Xcode16上报错的问题解决了吗？

大哥 这个解决了吗
